#!/bin/bash
# Secrets Generation Script for Meal Planner Application
# This script generates secure random passwords and stores them in Docker secrets files
# Usage: ./scripts/generate-secrets.sh

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Secrets directory
SECRETS_DIR="./secrets"

# Function to generate a secure random password
generate_password() {
    local length=${1:-32}
    openssl rand -base64 48 | tr -d "=+/" | cut -c1-${length}
}

# Function to generate a secure JWT secret (longer)
generate_jwt_secret() {
    openssl rand -base64 64 | tr -d "=+/" | cut -c1-64
}

echo -e "${GREEN}=== Meal Planner Secrets Generator ===${NC}"
echo ""

# Check if secrets directory exists
if [ -d "$SECRETS_DIR" ]; then
    echo -e "${YELLOW}Warning: Secrets directory already exists.${NC}"
    read -p "Do you want to regenerate all secrets? This will overwrite existing secrets. (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${RED}Aborted. No secrets were changed.${NC}"
        exit 1
    fi
    echo -e "${YELLOW}Backing up existing secrets to secrets.backup...${NC}"
    cp -r "$SECRETS_DIR" "${SECRETS_DIR}.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Create secrets directory
mkdir -p "$SECRETS_DIR"

echo -e "${GREEN}Generating secure secrets...${NC}"
echo ""

# Generate PostgreSQL password
echo -n "$(generate_password 32)" > "$SECRETS_DIR/postgres_password.txt"
echo -e "✓ Generated PostgreSQL password"

# Generate Redis password
echo -n "$(generate_password 32)" > "$SECRETS_DIR/redis_password.txt"
echo -e "✓ Generated Redis password"

# Generate JWT secret
echo -n "$(generate_jwt_secret)" > "$SECRETS_DIR/jwt_secret.txt"
echo -e "✓ Generated JWT secret"

# Generate JWT refresh secret
echo -n "$(generate_jwt_secret)" > "$SECRETS_DIR/jwt_refresh_secret.txt"
echo -e "✓ Generated JWT refresh secret"

# Generate session secret
echo -n "$(generate_password 48)" > "$SECRETS_DIR/session_secret.txt"
echo -e "✓ Generated session secret"

# Set proper permissions (read-only for owner)
chmod 600 "$SECRETS_DIR"/*.txt
echo ""
echo -e "${GREEN}✓ All secrets generated successfully!${NC}"
echo -e "${YELLOW}⚠ Secrets are stored in: $SECRETS_DIR${NC}"
echo -e "${YELLOW}⚠ These files contain sensitive data and should NEVER be committed to version control${NC}"
echo ""

# Create .env file with references to secrets (for local development)
ENV_FILE="./backend/.env"
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${GREEN}Creating backend/.env file with secret references...${NC}"
    cat > "$ENV_FILE" << 'EOF'
# Backend Environment Variables
# Generated by generate-secrets.sh

# Server Configuration
NODE_ENV=development
PORT=3000
HOST=0.0.0.0

# Database (secrets loaded from files in Docker)
DATABASE_URL=postgresql://mealplanner:$(cat /run/secrets/postgres_password)@localhost:5432/meal_planner

# Redis (secrets loaded from files in Docker)
REDIS_URL=redis://:$(cat /run/secrets/redis_password)@localhost:6379
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=$(cat /run/secrets/redis_password)

# JWT Configuration (secrets loaded from files in Docker)
JWT_SECRET=$(cat /run/secrets/jwt_secret)
JWT_REFRESH_SECRET=$(cat /run/secrets/jwt_refresh_secret)
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# CORS Configuration
CORS_ORIGIN=http://localhost:5173
ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000

# File Upload
MAX_FILE_SIZE=5242880
UPLOAD_DIR=./uploads

# External APIs (Optional for MVP)
SPOONACULAR_API_KEY=
EDAMAM_APP_ID=
EDAMAM_APP_KEY=

# Rate Limiting
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX_REQUESTS=100

# Logging
LOG_LEVEL=debug
LOG_FORMAT=dev

# Session
SESSION_SECRET=$(cat /run/secrets/session_secret)
EOF
    echo -e "${GREEN}✓ Created backend/.env file${NC}"
else
    echo -e "${YELLOW}⚠ backend/.env already exists. Skipping creation.${NC}"
    echo -e "${YELLOW}  You may need to manually update it to reference the new secrets.${NC}"
fi

echo ""
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo ""
echo -e "Next steps:"
echo -e "1. Review the generated secrets in: ${YELLOW}$SECRETS_DIR${NC}"
echo -e "2. Start your services with: ${YELLOW}docker-compose up -d${NC}"
echo -e "3. For local development without Docker, manually set environment variables from secrets files"
echo ""
echo -e "${RED}IMPORTANT: Add '$SECRETS_DIR/' to your .gitignore if not already present!${NC}"

# Made with Bob
