#!/bin/bash
# Secrets Generation Script for Meal Planner Application - Enhanced Security Edition
# This script generates secure random passwords and stores them in Docker/Podman secrets
# files with metadata and integrity checksums.
# Usage: ./scripts/generate-secrets.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=utilities.sh
source "$SCRIPT_DIR/utilities.sh"

# Portable sha256 — macOS ships shasum, Linux ships sha256sum
sha256_file() {
    if command -v sha256sum &>/dev/null; then
        sha256sum "$1" | cut -d' ' -f1
    else
        shasum -a 256 "$1" | cut -d' ' -f1
    fi
}

# Portable future-date — macOS date uses -v, GNU date uses -d
future_date() {
    local days=$1
    if date -v+${days}d &>/dev/null 2>&1; then
        date -u -v+${days}d +"%Y-%m-%dT%H:%M:%SZ"
    elif date -u -d "+${days} days" &>/dev/null 2>&1; then
        date -u -d "+${days} days" +"%Y-%m-%dT%H:%M:%SZ"
    else
        echo "null"
    fi
}

# Secrets directory
SECRETS_DIR="./secrets"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ROTATION_STATUS_FILE="$PROJECT_ROOT/docs/SECRET_ROTATION_STATUS.json"
ROTATION_MANIFEST="$(mktemp)"
trap 'rm -f "$ROTATION_MANIFEST"' EXIT

# Function to generate a secure random password
generate_password() {
    local length=${1:-32}
    openssl rand -base64 48 | tr -d "\n=+/" | cut -c1-${length}
}

# Function to generate a secure JWT secret (longer)
generate_jwt_secret() {
    openssl rand -base64 64 | tr -d "\n=+/" | cut -c1-64
}

# Function to generate secret with metadata and checksum
generate_secret_with_metadata() {
    local name=$1
    local length=$2
    local description=$3

    # Generate the secret. openssl rand -base64 wraps output at 64 chars/line for
    # anything longer than that, and `cut -c1-N` truncates per line rather than
    # across the whole stream — without stripping newlines first, the embedded
    # line breaks survive into the secret (and broke DATABASE_URL on rotation,
    # see #364). Strip them before cut so the truncation is on one continuous line.
    local secret=$(openssl rand -base64 $((length * 2)) | tr -d "\n=+/" | cut -c1-${length})
    
    # Write secret to file
    echo -n "$secret" > "$SECRETS_DIR/${name}.txt"
    chmod 600 "$SECRETS_DIR/${name}.txt"
    
    # Generate and write checksum
    sha256_file "$SECRETS_DIR/${name}.txt" > "$SECRETS_DIR/${name}.txt.sha256"
    chmod 600 "$SECRETS_DIR/${name}.txt.sha256"

    # Generate and write metadata
    cat > "$SECRETS_DIR/${name}.txt.metadata" << EOF
{
  "name": "${name}",
  "description": "${description}",
  "createdAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "expiresAt": "$(future_date 90)",
  "rotationDue": "$(future_date 75)",
  "algorithm": "openssl-rand-base64",
  "length": ${length},
  "version": 1
}
EOF
    chmod 600 "$SECRETS_DIR/${name}.txt.metadata"

    # Record to the (git-tracked, non-secret) rotation manifest so the weekly
    # maintenance routine — which never has filesystem access to $SECRETS_DIR —
    # can still tell when this secret is due for rotation.
    echo "${name}|$(date -u +"%Y-%m-%dT%H:%M:%SZ")|$(future_date 90)" >> "$ROTATION_MANIFEST"
}

# Function to write docs/SECRET_ROTATION_STATUS.json from the manifest built
# during this run. Contains only names and dates — never secret values — so
# it's safe to commit and readable by the cloud maintenance routine.
write_rotation_status_file() {
    mkdir -p "$(dirname "$ROTATION_STATUS_FILE")"

    {
        echo "{"
        echo "  \"_comment\": \"Generated by scripts/generate-secrets.sh — contains no secret values. Read by docs/WEEKLY_MAINTENANCE.md's secret rotation check.\","
        echo "  \"rotationPolicyDays\": 90,"
        echo "  \"lastRunAt\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\","
        echo "  \"secrets\": {"
        local first=true
        while IFS='|' read -r name created due; do
            [ -z "$name" ] && continue
            if [ "$first" = true ]; then
                first=false
            else
                echo ","
            fi
            printf '    "%s": { "lastRotated": "%s", "dueBy": "%s" }' "$name" "$created" "$due"
        done < "$ROTATION_MANIFEST"
        echo ""
        echo "  }"
        echo "}"
    } > "$ROTATION_STATUS_FILE"
}

# Function to backup existing secret as previous version
backup_as_previous() {
    local name=$1
    
    if [ -f "$SECRETS_DIR/${name}.txt" ]; then
        cp "$SECRETS_DIR/${name}.txt" "$SECRETS_DIR/${name}.txt.previous"
        chmod 600 "$SECRETS_DIR/${name}.txt.previous"
    fi
}

# -y/--yes: skip the confirmation prompt, for unattended invocation from
# scripts/rotate-secrets-if-due.sh (cron). Manual runs default to interactive.
NON_INTERACTIVE=false
for arg in "$@"; do
    case "$arg" in
        -y|--yes) NON_INTERACTIVE=true ;;
    esac
done

section "Secrets Generator" "🔐"
echo -e "  ${DIM}Enhanced Security Edition — metadata + integrity checksums${NC}"

# Check if secrets directory exists
if [ -d "$SECRETS_DIR" ]; then
    section "Existing Secrets" "🔐"

    existing_files=("$SECRETS_DIR"/*.txt)
    existing_count=0
    [ -e "${existing_files[0]}" ] && existing_count=${#existing_files[@]}
    echo -e "  ${YELLOW}⚠️  ${existing_count} existing secret file(s) in ${SECRETS_DIR}/ will be regenerated and overwritten:${NC}"
    for f in "${existing_files[@]}"; do
        [ -f "$f" ] && echo -e "     ${DIM}- $(basename "$f")${NC}"
    done
    echo -e "  ${DIM}(a full timestamped backup of ${SECRETS_DIR}/ is taken first)${NC}"
    echo ""

    if [ "$NON_INTERACTIVE" = true ]; then
        echo -e "  ${BLUE}ℹ️  --yes passed — regenerating without prompting.${NC}"
    else
        read -p "  $(echo -e "${RED}Regenerate all secrets now? This overwrites the files above. [y/N]:${NC}") " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo -e "  ${RED}✗${NC}  Aborted. No secrets were changed."
            exit 1
        fi
    fi
    echo ""

    start_spinner "Backing up existing secrets directory"
    backup_dir="${SECRETS_DIR}.backup.$(date +%Y%m%d_%H%M%S)"
    cp -r "$SECRETS_DIR" "$backup_dir"
    stop_spinner ok
    echo -e "  ${DIM}${backup_dir}${NC}"
    echo ""

    start_spinner "Preparing previous versions for rotation support"
    backup_as_previous "postgres_password"
    backup_as_previous "jwt_secret"
    backup_as_previous "jwt_refresh_secret"
    backup_as_previous "session_secret"
    backup_as_previous "redis_password"
    backup_as_previous "grafana_admin_password"
    stop_spinner ok
fi

# Create secrets directory
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

section "Generating Secrets" "🔐"

start_spinner "postgres_password — PostgreSQL database password (32 chars)"
generate_secret_with_metadata "postgres_password" 32 "PostgreSQL database password"
stop_spinner ok

start_spinner "jwt_secret — JWT access token signing secret (64 chars)"
generate_secret_with_metadata "jwt_secret" 64 "JWT access token signing secret"
stop_spinner ok

start_spinner "jwt_refresh_secret — JWT refresh token signing secret (64 chars)"
generate_secret_with_metadata "jwt_refresh_secret" 64 "JWT refresh token signing secret"
stop_spinner ok

start_spinner "session_secret — Session / CSRF signing secret (48 chars)"
generate_secret_with_metadata "session_secret" 48 "Session / CSRF signing secret"
stop_spinner ok

start_spinner "redis_password — Redis authentication password (32 chars)"
generate_secret_with_metadata "redis_password" 32 "Redis authentication password"
stop_spinner ok

start_spinner "grafana_admin_password — Grafana admin login (32 chars, monitoring overlay only)"
generate_secret_with_metadata "grafana_admin_password" 32 "Grafana admin login password"
stop_spinner ok

start_spinner "Writing rotation status file"
write_rotation_status_file
stop_spinner ok
echo -e "  ${DIM}$ROTATION_STATUS_FILE (safe to commit — no secret values)${NC}"

echo ""
echo -e "  ${GREEN}✓${NC}  All secrets generated successfully."
echo -e "  ${YELLOW}⚠️  Stored in ${SECRETS_DIR} — these files contain sensitive data and must NEVER be committed.${NC}"

section "Secret Details" "🔐"
for secret_file in "$SECRETS_DIR"/*.txt; do
    if [ -f "$secret_file" ]; then
        secret_name=$(basename "$secret_file" .txt)
        if [ "$secret_name" != "*.txt" ]; then
            secret_length=$(wc -c < "$secret_file" | tr -d ' ')
            checksum_file="${secret_file}.sha256"
            metadata_file="${secret_file}.metadata"
            
            echo -e "  ${GREEN}✓${NC} ${BOLD}${secret_name}${NC}"
            echo -e "     Length: ${secret_length} characters"

            if [ -f "$checksum_file" ]; then
                checksum=$(cat "$checksum_file")
                echo -e "     Checksum: ${DIM}${checksum:0:16}...${NC}"
            fi

            if [ -f "$metadata_file" ]; then
                rotation_due=$(grep -o '"rotationDue": "[^"]*"' "$metadata_file" | cut -d'"' -f4)
                if [ "$rotation_due" != "null" ]; then
                    echo -e "     Rotation due: ${rotation_due}"
                fi
            fi
            echo ""
        fi
    fi
done

# Create .env file with references to secrets (for local development)
section "Environment File" "🔐"
ENV_FILE="./backend/.env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << 'EOF'
# Backend Environment Variables
# Generated by generate-secrets.sh - Enhanced Security Edition

# Server Configuration
NODE_ENV=development
PORT=3000
HOST=0.0.0.0

# Security Configuration
ALLOW_SECRET_ENV_FALLBACK=true
ENABLE_SECRET_AUDIT_LOG=false

# Database (secrets loaded from files in Docker)
DATABASE_URL=postgresql://mealplanner:$(cat /run/secrets/postgres_password)@localhost:5432/meal_planner
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=meal_planner
POSTGRES_USER=mealplanner

# JWT Configuration (secrets loaded from files in Docker)
# Shorter token lifetimes for improved security
JWT_EXPIRES_IN=10m
JWT_REFRESH_EXPIRES_IN=1d

# CORS Configuration
CORS_ORIGIN=http://localhost:5173
ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000

# File Upload
MAX_FILE_SIZE=5242880
UPLOAD_DIR=./uploads

# External APIs (Optional for MVP)
SPOONACULAR_API_KEY=
EDAMAM_APP_ID=
EDAMAM_APP_KEY=

# Rate Limiting
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX_REQUESTS=100

# Logging
LOG_LEVEL=debug
LOG_FORMAT=dev

# Password Policy Configuration
PASSWORD_MIN_LENGTH=8
PASSWORD_MAX_LENGTH=128
PASSWORD_REQUIRE_UPPERCASE=true
PASSWORD_REQUIRE_LOWERCASE=true
PASSWORD_REQUIRE_NUMBER=true
PASSWORD_REQUIRE_SPECIAL=true
PASSWORD_MIN_UPPERCASE=1
PASSWORD_MIN_LOWERCASE=1
PASSWORD_MIN_NUMBERS=1
PASSWORD_MIN_SPECIAL=1
EOF
    echo -e "  ${GREEN}✓${NC}  Created backend/.env file"
else
    echo -e "  ${YELLOW}⚠️  backend/.env already exists — skipped.${NC}"
    echo -e "     You may need to manually update it to reference the new secrets."
fi

section "Summary" "🍽️"
echo -e "  ${BOLD}Next steps:${NC}"
echo -e "    1. Review the generated secrets in: ${YELLOW}$SECRETS_DIR${NC}"
echo -e "    2. Start your services with: ${YELLOW}podman-compose up -d${NC}"
echo -e "    3. For local development without containers, manually set environment variables from secrets files"
echo -e "    4. Commit the updated rotation status file: ${YELLOW}git add docs/SECRET_ROTATION_STATUS.json && git commit -m 'chore: record secret rotation'${NC}"
echo ""
echo -e "  ${BLUE}Security features:${NC}"
echo -e "    ${GREEN}✓${NC} Cryptographically secure random generation"
echo -e "    ${GREEN}✓${NC} SHA-256 integrity checksums"
echo -e "    ${GREEN}✓${NC} Metadata with expiration tracking"
echo -e "    ${GREEN}✓${NC} Previous version backup for rotation support"
echo -e "    ${GREEN}✓${NC} Timestamped backups of old secrets"
echo ""
echo -e "  ${YELLOW}Security reminders:${NC}"
echo -e "    • Rotate secrets every 90 days (tracked in metadata)"
echo -e "    • Never commit secrets to version control"
echo -e "    • Use different secrets for each environment"
echo -e "    • Keep backups encrypted and secure"
echo ""
echo -e "  ${RED}⚠️  IMPORTANT: Add '$SECRETS_DIR/' to your .gitignore if not already present!${NC}"

