#!/bin/bash
# Raspberry Pi Setup Script
# Generates environment-specific documentation and configures auto-start

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=utilities.sh
source "$SCRIPT_DIR/utilities.sh"

echo -e "${BLUE}=== Meal Planner Pi Setup ===${NC}"
echo ""

# Get system information
HOSTNAME=$(hostname)
IP_ADDRESS=$(hostname -I | awk '{print $1}')
PI_MODEL=$(cat /proc/device-tree/model 2>/dev/null | tr -d '\0' || echo "Unknown Pi Model")
TOTAL_RAM=$(free -h | awk '/^Mem:/ {print $2}')
AVAILABLE_DISK=$(df -h / | awk 'NR==2 {print $4}')

echo -e "${BLUE}System Information:${NC}"
echo -e "  Hostname: ${GREEN}${HOSTNAME}${NC}"
echo -e "  IP Address: ${GREEN}${IP_ADDRESS}${NC}"
echo -e "  Model: ${GREEN}${PI_MODEL}${NC}"
echo -e "  Total RAM: ${GREEN}${TOTAL_RAM}${NC}"
echo -e "  Available Disk: ${GREEN}${AVAILABLE_DISK}${NC}"
echo ""

# Generate environment-specific documentation
DOC_FILE="PI_QUICK_START_${HOSTNAME}.md"

echo -e "${YELLOW}📝 Generating environment-specific documentation...${NC}"

cat > "$DOC_FILE" << EOF
# Meal Planner Quick Start - ${HOSTNAME}

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')  
**Hostname:** ${HOSTNAME}  
**IP Address:** ${IP_ADDRESS}  
**Model:** ${PI_MODEL}  
**RAM:** ${TOTAL_RAM}

---

## Quick Access

**Web Application:** http://${IP_ADDRESS}:8080  
**Local Access:** http://localhost:8080  
**Health Check:** http://${IP_ADDRESS}:8080/health

---

## Essential Commands

### Start Application
\`\`\`bash
cd ~/mealplanner
./scripts/pi-run.sh
\`\`\`

### Stop Application
\`\`\`bash
cd ~/mealplanner
./scripts/pi-stop.sh
\`\`\`

### Restart Application
\`\`\`bash
cd ~/mealplanner
./scripts/pi-bounce.sh
\`\`\`

### Check Health
\`\`\`bash
cd ~/mealplanner
./scripts/pi-health-check.sh
\`\`\`

### View Logs
\`\`\`bash
cd ~/mealplanner
# All services
podman-compose -f podman-compose.pi.yml logs -f

# Specific service
podman-compose -f podman-compose.pi.yml logs -f backend
podman-compose -f podman-compose.pi.yml logs -f postgres
\`\`\`

### Check Container Status
\`\`\`bash
podman ps
podman stats
\`\`\`

---

## Troubleshooting

### Application Won't Start
\`\`\`bash
# Check if images are loaded
podman images | grep meals

# If not loaded, load them
cd ~/mealplanner
./scripts/load-pi-images.sh

# Then start
./scripts/pi-run.sh
\`\`\`

### High Memory Usage
\`\`\`bash
# Check usage
free -h
podman stats

# Restart to clear memory
cd ~/mealplanner
./scripts/pi-bounce.sh
\`\`\`

### Disk Space Issues
\`\`\`bash
# Check usage
df -h
podman system df

# Clean up
sudo journalctl --vacuum-size=50M
podman system prune
\`\`\`

### View Container Logs for Errors
\`\`\`bash
cd ~/mealplanner
podman-compose -f podman-compose.pi.yml logs --tail=100 backend
podman-compose -f podman-compose.pi.yml logs --tail=100 postgres
\`\`\`

---

## Maintenance

### Daily Health Check
\`\`\`bash
cd ~/mealplanner
./scripts/pi-health-check.sh
\`\`\`

### Weekly Cleanup
\`\`\`bash
# Remove stopped containers and unused images
podman system prune
\`\`\`

### Monthly Database Maintenance
\`\`\`bash
# Vacuum and analyze database
podman exec meals-postgres psql -U mealplanner -d meal_planner -c "VACUUM ANALYZE;"
\`\`\`

### Backup Database
\`\`\`bash
# Create backup
podman exec meals-postgres pg_dump -U mealplanner meal_planner > backup-\$(date +%Y%m%d).sql
\`\`\`

---

## System Resources

**Memory Allocation:**
- PostgreSQL: 160MB limit
- Redis: 32MB limit
- Backend: 320MB limit
- Nginx: 48MB limit
- **Total:** 560MB (leaves ~1.44GB for OS + buffers on a 2GB Pi)

**Performance Targets:**
- CPU Load: <2.0 (warning >2.0, critical >3.5)
- Memory: <70% (warning >70%, critical >85%)
- Disk: <75% (warning >75%, critical >85%)
- Temperature: <65°C (warning >65°C, critical >70°C)

---

## Auto-Start Configuration

EOF

# Check if auto-start is configured
if systemctl is-enabled mealplanner.service &>/dev/null; then
    cat >> "$DOC_FILE" << EOF
**Status:** ✅ Auto-start is ENABLED

The application will automatically start when the Pi boots.

To disable auto-start:
\`\`\`bash
sudo systemctl disable mealplanner.service
\`\`\`
EOF
else
    cat >> "$DOC_FILE" << EOF
**Status:** ❌ Auto-start is NOT configured

To enable auto-start on boot, run:
\`\`\`bash
cd ~/mealplanner
./scripts/pi-setup.sh
# Choose 'yes' when prompted for auto-start
\`\`\`
EOF
fi

cat >> "$DOC_FILE" << EOF

---

## Support

For detailed documentation, see:
- [Raspberry Pi Deployment Guide](docs/RASPBERRY_PI_DEPLOYMENT_GUIDE.md)
- [Pi Optimization Proposal](docs/PI_OPTIMIZATION_PROPOSAL.md)

---

*Generated by pi-setup.sh*
EOF

echo -e "${GREEN}✓ Documentation generated: ${DOC_FILE}${NC}"
echo ""

# Ask about auto-start configuration
echo -e "${YELLOW}🚀 Auto-Start Configuration${NC}"
echo ""
echo "Would you like the Meal Planner to start automatically when the Pi boots?"
echo "This ensures the application is always available after a restart or power cycle."
echo ""
read -p "Enable auto-start? (y/N): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}Setting up auto-start...${NC}"
    
    # Create systemd service file
    SERVICE_FILE="/tmp/mealplanner.service"
    cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Meal Planner Application
After=network-online.target
Wants=network-online.target
Requires=podman.socket

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutStartSec=300
WorkingDirectory=$(pwd)
ExecStart=$(pwd)/scripts/pi-run.sh --force
ExecStop=$(pwd)/scripts/pi-stop.sh
User=$(whoami)
Group=$(whoami)
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    # Install service
    sudo mv "$SERVICE_FILE" /etc/systemd/system/mealplanner.service
    sudo chmod 644 /etc/systemd/system/mealplanner.service

    # Enable and start service
    sudo systemctl daemon-reload
    sudo systemctl enable mealplanner.service

    echo -e "${GREEN}✓ Auto-start configured successfully!${NC}"

    # Install delayed Zero W deployment timer if ClusterHAT is present
    if detect_clusterhat; then
        echo -e "${YELLOW}ClusterHAT detected — installing delayed Zero W deployment timer...${NC}"

        ZEROS_SERVICE="/tmp/mealplanner-zeros.service"
        cat > "$ZEROS_SERVICE" << EOF
[Unit]
Description=Meal Planner — Deploy backend to Zero W nodes
After=mealplanner.service
Requires=mealplanner.service

[Service]
Type=oneshot
WorkingDirectory=$(pwd)
ExecStart=$(pwd)/scripts/pi-run.sh --zeros-only --zero-user=$CLUSTERHAT_ZERO_USER
User=$(whoami)
TimeoutStartSec=600
StandardOutput=journal
StandardError=journal
SyslogIdentifier=mealplanner-zeros
EOF

        ZEROS_TIMER="/tmp/mealplanner-zeros.timer"
        cat > "$ZEROS_TIMER" << 'EOF'
[Unit]
Description=Meal Planner — Deploy to Zeros after boot

[Timer]
OnBootSec=120

[Install]
WantedBy=timers.target
EOF

        sudo mv "$ZEROS_SERVICE" /etc/systemd/system/mealplanner-zeros.service
        sudo mv "$ZEROS_TIMER" /etc/systemd/system/mealplanner-zeros.timer
        sudo chmod 644 /etc/systemd/system/mealplanner-zeros.service
        sudo chmod 644 /etc/systemd/system/mealplanner-zeros.timer
        sudo systemctl daemon-reload
        sudo systemctl enable mealplanner-zeros.timer

        echo -e "${GREEN}✓ Zero W deployment timer installed (fires 2 min after boot)${NC}"
    fi

    echo ""
    echo -e "${BLUE}Service commands:${NC}"
    echo -e "  Start:   ${GREEN}sudo systemctl start mealplanner${NC}"
    echo -e "  Stop:    ${GREEN}sudo systemctl stop mealplanner${NC}"
    echo -e "  Status:  ${GREEN}sudo systemctl status mealplanner${NC}"
    echo -e "  Disable: ${GREEN}sudo systemctl disable mealplanner${NC}"
    echo ""
    
    # Ask if they want to start now
    read -p "Start the application now? (Y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        echo -e "${YELLOW}Starting application...${NC}"
        sudo systemctl start mealplanner
        sleep 5
        echo ""
        echo -e "${GREEN}✓ Application started!${NC}"
        echo -e "${BLUE}Access at: http://${IP_ADDRESS}:8080${NC}"
    fi
else
    echo -e "${BLUE}ℹ️  Auto-start not configured${NC}"
    echo -e "You can run this script again anytime to enable it."
fi

# Install weekly Podman image prune cron job
echo ""
echo -e "${YELLOW}🧹 Installing weekly image prune cron job...${NC}"
sudo tee /etc/cron.weekly/podman-prune > /dev/null << 'EOF'
#!/bin/bash
# Remove dangling Podman images to reclaim SD card space.
podman image prune -f >> /var/log/podman-prune.log 2>&1
EOF
sudo chmod 755 /etc/cron.weekly/podman-prune
echo -e "${GREEN}✓ Weekly image prune installed (/etc/cron.weekly/podman-prune)${NC}"

# Ask about Glances monitoring
echo ""
echo -e "${YELLOW}📊 Monitoring (Glances)${NC}"
echo ""
echo "Would you like to install Glances cluster monitoring?"
echo "Once running, it will be accessible at http://${IP_ADDRESS}:8080/monitoring"
echo ""
read -p "Install Glances? (y/N): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    GLANCES_FLAGS=""
    read -p "Also install on Zero W cluster nodes? (y/N): " -n 1 -r
    echo ""
    [[ $REPLY =~ ^[Yy]$ ]] && GLANCES_FLAGS="--clusterhat"

    echo -e "${YELLOW}Installing Glances...${NC}"
    chmod +x ./scripts/install-glances.sh
    # shellcheck disable=SC2086
    ./scripts/install-glances.sh $GLANCES_FLAGS
fi

echo ""
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo ""
echo -e "${BLUE}📄 Your quick start guide: ${GREEN}${DOC_FILE}${NC}"
echo -e "${BLUE}🌐 Access application: ${GREEN}http://${IP_ADDRESS}:8080${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo -e "  1. Read your quick start guide: ${GREEN}cat ${DOC_FILE}${NC}"
echo -e "  2. Check application health: ${GREEN}./scripts/pi-health-check.sh${NC}"
echo -e "  3. View logs: ${GREEN}podman-compose -f podman-compose.pi.yml logs -f${NC}"
echo ""

