#!/bin/bash
echo "# Issue Prioritization"
echo ""
echo "**Last Updated:** $(date +%Y-%m-%d)"
echo ""
echo "This file reflects the current state of GitHub issues by priority. Issues are managed via GitHub labels (P0-critical, P1-high, P2-medium, P3-low, P4-future)."
echo ""
echo "## 🔴 P0 - CRITICAL (Drop Everything)"
echo "Issues that make the application unusable or cause data loss."
echo ""
gh issue list --state open --label "P0-critical" --json number,title | jq -r '.[] | "- #\(.number) - \(.title)"'
if [ $(gh issue list --state open --label "P0-critical" --json number | jq '. | length') -eq 0 ]; then
  echo "**No P0 issues currently open** ✅"
fi
echo ""
echo "## 🔴 P1 - HIGH (Current Sprint)"
echo "Issues that significantly impact core functionality or user experience."
echo ""
gh issue list --state open --label "P1-high" --json number,title | jq -r '.[] | "- #\(.number) - \(.title)"'
if [ $(gh issue list --state open --label "P1-high" --json number | jq '. | length') -eq 0 ]; then
  echo "**No P1 issues currently open**"
fi
echo ""
echo "## 🟡 P2 - MEDIUM (Next Sprint)"
echo "Important improvements that enhance functionality but don't block core workflows."
echo ""
gh issue list --state open --label "P2-medium" --json number,title | jq -r '.[] | "- #\(.number) - \(.title)"'
echo ""
echo "## 🟢 P3 - LOW (Backlog)"
echo "Nice-to-have improvements and minor UX enhancements."
echo ""
gh issue list --state open --label "P3-low" --json number,title | jq -r '.[] | "- #\(.number) - \(.title)"'
echo ""
echo "## 📋 P4 - FUTURE ENHANCEMENTS"
echo "Feature requests and enhancements for future releases."
echo ""
gh issue list --state open --label "P4-future" --json number,title | jq -r '.[] | "- #\(.number) - \(.title)"'
echo ""
echo "## ⚠️ Unprioritized Issues"
echo "Issues without priority labels that need to be triaged."
echo ""
gh issue list --state open --json number,title,labels --limit 100 | jq -r '.[] | select(.labels | map(.name | startswith("P")) | any | not) | "- #\(.number) - \(.title)"'
echo ""
echo "## Priority Guidelines"
echo ""
echo "### P0 - CRITICAL"
echo "- Application is down or unusable"
echo "- Data loss or corruption"
echo "- Security vulnerabilities"
echo "- **Action:** Drop everything and fix immediately"
echo ""
echo "### P1 - HIGH"
echo "- Core features broken or severely degraded"
echo "- Significant user pain points"
echo "- Blocks important workflows"
echo "- **Action:** Fix in current sprint (1-2 weeks)"
echo ""
echo "### P2 - MEDIUM"
echo "- Feature improvements"
echo "- Moderate user pain points"
echo "- Quality of life enhancements"
echo "- **Action:** Plan for next sprint (2-4 weeks)"
echo ""
echo "### P3 - LOW"
echo "- Minor UX improvements"
echo "- Edge cases"
echo "- Nice-to-have features"
echo "- **Action:** Backlog, address when time permits"
echo ""
echo "### P4 - FUTURE"
echo "- New features"
echo "- Major enhancements"
echo "- Long-term improvements"
echo "- **Action:** Plan for future releases"
echo ""
echo "## How to Update Priorities"
echo ""
echo "1. Use GitHub labels to set priority (P0-critical, P1-high, P2-medium, P3-low, P4-future)"
echo "2. Run \`./scripts/update-issue-priorities.sh\` to regenerate this file"
echo "3. Commit changes with descriptive message"
echo "4. Communicate priority changes to team"
